
atlantic-objs:=aq_main.o aq_nic.o aq_pci_func.o aq_nic.o aq_vec.o aq_ring.o \
  aq_hw_utils.o aq_ethtool.o hw_atl/hw_atl_a0.o hw_atl/hw_atl_b0.o hw_atl/hw_atl_utils.o\
  hw_atl/hw_atl_llh.o

obj-m:=atlantic.o

